#############
## validation
## will be added
#validate(config, "schema/config.schema.yaml")
#validate(samples, "schema/samples.schema.yaml")

#######################
## loading rule modules
include: "rules/common.smk"                  ## self-defined functions
include: "rules/cellranger_arc.smk"          ## cellranger-arc mapping, QC and joint cell calling;
include: "rules/individual_sample.smk"       ## primariy and secondary analysis of indiviudal sample
#include: "rules/multiple_samples.smk"        ## horizonal and vertical integration of multiple samples

#include: "rules/main_seurat.smk"
#include: "rules/integration.smk"

###################
rule all:
    input:
        ## set config["test_cellranger_arc"] = true to only test cellranger_arc.smk
        (
            expand(
                "arc_count/{samples}/outs/atac_fragments.tsv.gz",
                samples=SAMPLES["sample_id"],
            )
            if config.get("test_cellranger_arc", False)
            else get_rule_all_input()
        )