################################################################################
## extended analyses based on integrated RNA and ATAC for each individual sample
## Part 2: Gene regulatory network analysis
################################################################################

##############################
### parse and assign arguments
##############################
{
suppressPackageStartupMessages(library("argparse"))

# create parser object
parser <- ArgumentParser()

parser$add_argument("-s", "--sample_id", required=TRUE,
                    help = "Unique sample ID")
parser$add_argument("-e1", "--extended_pre_grn_seurat_object", required=TRUE,
                    help = "the seurat object generated by extended analyses part1")
parser$add_argument("-pipe", "--pipe_dir", required=TRUE,
                    help = "The PATH to iSHARC pipeline, which local dependences included")
parser$add_argument("-t", "--threads", type = "integer", default = 12,
                    help = "Number of cores for the parallelization")
parser$add_argument("-fgm", "--future_globals_maxSize", type = "integer", default = 12,
                    help = "Maximum memory in GB for the future parallelization global variables")

args <- parser$parse_args()
print(args)

sample_id <- args$sample_id
extended_pre_grn_file <- args$extended_pre_grn_seurat_object
pipe_dir <- args$pipe_dir

out_dir <- paste0(getwd(), "/individual_samples/", sample_id, "/")
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

log_path <- paste0(out_dir, sample_id, "_extended_analyses_part2_debug.log")
log_step <- function(msg) {
  cat(format(Sys.time(), "%Y-%m-%d %H:%M:%S"), " | ", msg, "\n",
      file = log_path, append = TRUE)
}
log_step("Part2 script start")

options(error = function() {
  log_step("ERROR encountered. Dumping traceback.")
  log_step(paste0("Last error message: ", geterrmessage()))
  tb <- utils::capture.output(traceback())
  if (length(tb) > 0) {
    cat(paste(tb, collapse = "\n"), "\n", file = log_path, append = TRUE)
  }
  quit(status = 1)
})

run_step <- function(step_name, expr) {
  log_step(paste0("[START] ", step_name))
  t0 <- Sys.time()
  out <- tryCatch(
    eval.parent(substitute(expr)),
    error = function(e) {
      log_step(paste0("[FAIL] ", step_name, " | ", conditionMessage(e)))
      stop(e)
    }
  )
  dt <- round(as.numeric(difftime(Sys.time(), t0, units = "secs")), 2)
  log_step(paste0("[DONE] ", step_name, " | ", dt, " sec"))
  out
}

}

############################
### loading required packages
#############################
log_step("Loading required packages")
suppressMessages(library(Seurat))
suppressMessages(library(Signac))
suppressMessages(library(BSgenome.Hsapiens.UCSC.hg38))

suppressMessages(library(dplyr))
suppressMessages(library(tidygraph))
suppressMessages(library(tidyverse))
suppressMessages(library(ggplot2))
suppressMessages(library(ggraph))

suppressMessages(library(future))
plan("multicore", workers = args$threads)
options(future.globals.maxSize = args$future_globals_maxSize * 1024^3)

library(Pando)
suppressMessages(library(doParallel))

log_step("Packages loaded; sessionInfo below")
si <- utils::capture.output(sessionInfo())
cat(paste(si, collapse = "\n"), "\n", file = log_path, append = TRUE)

scMultiome <- run_step("Read pre-GRN Seurat object", readRDS(extended_pre_grn_file))
##############################################
##  GRN: TF-gene gene regulatory network (GRN)
##  Pando: https://quadbio.github.io/Pando/
##############################################
if(TRUE){

#########################################
## packages installed from "dependencies"
#  data('phastConsElements20Mammals.UCSC.hg38')  ## in /Pando-1.0.0/data
## pando curated motifs in /Pando-1.0.0/data

data('motifs')      ## PFM for 1590 TFs
data('motif2tf')
data('SCREEN.ccRE.UCSC.hg38')    ## regions are contrained to SCREEN candidate cREs

##################################################
## infer GRN based on combined cluster-specific DEGs
## regions are contained to SCREEN candidate cREs
{
  ## combined and unique DEGs
## combined and unique DEGs
  clusters <- levels(scMultiome)
  L <- length(clusters)
  all_degs <- vector()
  combined_grn_list <- list()  ## graph list for culster specific DEGs

  for(i in 1:L)
  {

    ## limited to cluster specific DEGs
    all_degs <- c(all_degs, rownames(scMultiome[['SCT']]@misc$DEGs[[i]]))
  }
  all_degs <- unique(all_degs)

  ## for testing
  ## all_degs <- rownames(scMultiome@assays$RNA@counts)[1:1000]


  #################
  ## initialization
  scMultiome_GRN <- initiate_grn(
    scMultiome,
    rna_assay = 'SCT',
    peak_assay = 'ATAC',
    regions = SCREEN.ccRE.UCSC.hg38)

  ################
  ## Scaning motif
  # Will select candidate regulatory regions near genes

  #  constrain to given gene list
  if(FALSE){
    patterning_genes <- read_tsv('patterning_genes.tsv')
    pattern_tfs <- patterning_genes %>%
      dplyr::filter(type=='Transcription factor') %>%
      dplyr::pull(symbol)
    motif2tf_use <- motif2tf %>%
      dplyr::filter(tf %in% pattern_tfs)
    motifs_use <- motifs[unique(motif2tf_use$motif)]
    motif2tf_use
  }


  scMultiome_GRN <- find_motifs(
    scMultiome_GRN,
    pfm = motifs,
    motif_tfs = motif2tf,
    genome = BSgenome.Hsapiens.UCSC.hg38
  )



  ################
  ## infering GRN
  registerDoParallel(args$threads)

  scMultiome_GRN  <- infer_grn(
    scMultiome_GRN ,
    peak_to_gene_method = 'Signac',
    ## limited to cluster specific DARs as target genes
    genes = all_degs,  # Combined DEGs
    parallel = T
  )

  ## summary of inferred GRN
  n_fit <- nrow(GetNetwork(scMultiome_GRN)@fit)

if(n_fit >= 1) {
    ## modules discovery
    scMultiome_GRN <- find_modules(
      scMultiome_GRN,
      p_thresh = 0.05,
      nvar_thresh = 2,
      min_genes_per_module = 5,
      rsq_thresh = 0.05
    )

  modules <- NetworkModules(scMultiome_GRN)@meta
  write.csv(modules, paste0(out_dir, sample_id, "_combined_WNN_clusters_specific_DEGs_GRN_Modules.csv"))

  featurs <- NetworkFeatures(scMultiome_GRN)

    ##
  modules_use <- NetworkModules(scMultiome_GRN)@meta %>%
      dplyr::filter(target%in%featurs, tf%in%featurs)

  n_modules <- nrow(modules_use)

    if(n_modules > 2) {
    scMultiome_GRN <- get_network_graph(scMultiome_GRN,
                                            rna_assay = "SCT",       ## using SCT normalized RNA
                                            umap_method = "none",    ## without UMAP embedding
                                            graph_name = "Combined_DEGs_GRN")

    ## saveRDS(scMultiome_GRN, paste0(out_dir, sample_id, "_scMultiome_GRN_for_testing.RDS"))

    ## g <- plot_network_graph(scMultiome_GRN , layout='fr') + ggtitle ("Combined_Clusters_Specific_DEGs")
    ## ggsave(paste0(out_dir, sample_id, "_combined_WNN_clusters_specific_DEGs_GRN.pdf"))
    ## might encounter: Error in NetworkGraph.Network(GetNetwork(object, network = network), graph = graph) :
    ## The requested graph "module_graph" does not exist.

    ## customize the GRN
    Combined_DEGs_GRN <-  NetworkGraph(scMultiome_GRN , graph='Combined_DEGs_GRN')  ## graph object

    ## get edges or nodes by:
    ## edges <- Combined_DEGs_GRN %>% activate(edges) %>% data.frame()
    ## nodes <- Combined_DEGs_GRN %>% activate(nodes) %>% data.frame()
    ## could modify tbl_graph separately and combine them afterward using:
    ## GRN_new <- tbl_graph(nodes = new_nodes, edges = new_edges)

    edge_color = c('-1'='darkgrey', '1'='orange')  ## darkgrey for repression and orange for activate
    node_fill_color = c("0" = "lightgrey", "1" = "Brown")
    node_color = c("0" = "white", "1" = "Black")

    tf_list <- unique(modules$tf)
    target_list <- unique(modules$target)
    target_tf <- intersect(target_list, tf_list)

    Combined_DEGs_GRN_mut <- Combined_DEGs_GRN %>%
                             activate(edges) %>%
                             mutate(dir = sign(estimate)) %>%
                             activate(nodes) %>%
                             mutate(name_label = ifelse(name %in% target_tf, name, ""), ## label tf_target
                                    isTF = ifelse(name %in% tf_list, "1", "0"),
                                    isTargetTF = ifelse(name %in% target_tf, "1", "0"))

    saveRDS(Combined_DEGs_GRN_mut, paste0(out_dir, sample_id, "_combined_WNN_clusters_specific_DEGs_GRN.RDS"))
    combined_grn_list[[1]] <- Combined_DEGs_GRN_mut

    g <- ggraph(Combined_DEGs_GRN_mut, layout='fr') +
         geom_edge_diagonal(aes(color=factor(dir)), width = 0.2) + scale_edge_color_manual(values=edge_color) +
         geom_node_point(aes(size = centrality, fill = factor(isTF), color = factor(isTargetTF)), shape=21) +
         scale_fill_manual(values = node_fill_color) + scale_color_manual(values = node_color) +
         geom_node_text(aes(label = name_label, size = centrality*0.75), repel=T) +
         theme_void() + theme(legend.position = "none") + ggtitle("Combined_DEGs_GRN")

    ggsave(paste0(out_dir, sample_id, "_combined_WNN_clusters_specific_DEGs_GRN.pdf"))

    }
 }

 print("The analysis of GRN based on combined cluster-specific DEGs has been successfully completed!!")

}



#######################################################
## infer GRN based on cluster-specific DEGs per cluster
## regions are contrained to SCREEN candidate cREs
{
  #################
  ## initialization
  ####################################
  ## subsetting by WNN based clusters

  clusters <- levels(scMultiome)
  L <- length(clusters)
  grn_list <- list()  ## graph list for culster specific DEGs
  k = 1

  for(i in 1:L)
  {
    print(i)

    ## limited to cluster specific DEGs
    n_deg <- nrow(scMultiome@assays$SCT@misc$DEGs[[i]])         ## number of DEGs

    ## requiring cluster with at least 30 samples
    ## based on https://leanscape.io/the-importance-of-identifying-the-right-sample-size-for-business-improvement/#:~:text=Why%20is%2030%20the%20minimum,as%20the%20sample%20size%20increases.
    #if(cluster_cnt[i] < 30 | length(dar_regions) < 2 ){
    if(length(n_deg) == 0){          ## for n_deg == Null

      next

    } else if (n_deg < 2){           ##  require at least more than 2 DEGs

      next

      } else {

      ## cluster subseting
      scMultiome_sub <- subset(scMultiome, idents = clusters[i])

      scMultiome_GRN <- initiate_grn(
        scMultiome_sub,
        rna_assay = 'SCT',
        peak_assay = 'ATAC',
        regions = SCREEN.ccRE.UCSC.hg38)

      # Will select candidate regulatory regions near genes
      scMultiome_GRN <- find_motifs(
        scMultiome_GRN,
        pfm = motifs,
        motif_tfs = motif2tf,
        genome = BSgenome.Hsapiens.UCSC.hg38
      )

      ################
      ## infering GRN
      registerDoParallel(args$threads)

      scMultiome_GRN  <- infer_grn(
        scMultiome_GRN ,
        peak_to_gene_method = 'Signac',
        ## limited to cluster specific DARs as target genes
        genes = rownames(scMultiome@assays$SCT@misc$DEGs[[i]]),  # target genes to consider
        parallel = T
      )

      ## summary of inferred GRN
      n_fit <- nrow(GetNetwork(scMultiome_GRN)@fit)

      if(n_fit < 1) {
        next
      } else {
        ## modules discovery
        scMultiome_GRN <- find_modules(
          scMultiome_GRN,
          p_thresh = 0.1,
          nvar_thresh = 2,
          min_genes_per_module = 1,
          rsq_thresh = 0.05
        )

        modules <- NetworkModules(scMultiome_GRN)@meta
        write.csv(modules, paste0(out_dir, sample_id, "_WNN_cluster_", clusters[i], "_specific_DEGs_GRN_Modules.csv"))

        featurs <- NetworkFeatures(scMultiome_GRN)

        ##
        modules_use <- NetworkModules(scMultiome_GRN)@meta %>%
          dplyr::filter(target%in%featurs, tf%in%featurs)

        n_modules <- nrow(modules_use)
        if(n_modules <= 2) {
          next
        } else {

          scMultiome_GRN <- get_network_graph(scMultiome_GRN,
                                              rna_assay = "SCT",       ## using SCT normalized RNA
                                              umap_method = "none",    ## without UMAP embedding
                                              graph_name = "Specific_DEGs_GRN")

          ## g <-  plot_network_graph(scMultiome_GRN, layout='fr')  + ggtitle(paste0("Cluster_",clusters[i], "_specific_DEGs"))
          ## ggsave(paste0(out_dir, sample_id, "_WNN_cluster_",clusters[i], "_specific_DEGs_GRN.pdf"))

          ## customize the GRN
          Specific_DEGs_GRN <-  NetworkGraph(scMultiome_GRN , graph='Specific_DEGs_GRN')  ## graph object

          edge_color = c('-1'='darkgrey', '1'='orange')  ## darkgrey for repression and orange for activate
          node_fill_color = c("0" = "lightgrey", "1" = "Brown")
          node_color = c("0" = "white", "1" = "Black")

          tf_list <- unique(modules$tf)
          target_list <- unique(modules$target)
          target_tf <- intersect(target_list, tf_list)

          Specific_DEGs_GRN_mut <- Specific_DEGs_GRN %>%
            activate(edges) %>%
            mutate(dir = sign(estimate)) %>%
            activate(nodes) %>%
            mutate(name_label = ifelse(name %in% target_tf, name, ""), ## label tf_target
                   isTF = ifelse(name %in% tf_list, "1", "0"),
                   isTargetTF = ifelse(name %in% target_tf, "1", "0"))

          g <- ggraph(Specific_DEGs_GRN_mut, layout='fr') +
            geom_edge_diagonal(aes(color=factor(dir)), width = 0.2) + scale_edge_color_manual(values=edge_color) +
            geom_node_point(aes(size = centrality, fill = factor(isTF), color = factor(isTargetTF)), shape=21) +
            scale_fill_manual(values = node_fill_color) + scale_color_manual(values = node_color) +
            geom_node_text(aes(label = name, size = centrality*0.75), repel=T) +
            theme_void() + theme(legend.position = "none") + ggtitle(paste0("Cluster_", clusters[i], "_specific_DEGs_GRN"))

          ggsave(paste0(out_dir, sample_id, "_WNN_cluster_", clusters[i], "_specific_DEGs_GRN.pdf"))

          grn_list[[k]] <- Specific_DEGs_GRN_mut
          names(grn_list)[k] <- paste0("WNN_cluster_", clusters[i], "_specific_DEGs_GRN")
          k = k + 1
        }

      }

    }

  }

  # saveRDS(grn_list, paste0(sample_id, "_cluster_specific_DEGs_GRN.RDS"))
  print("The analysis of GRN based on cluster-specific DEGs has been successfully completed!!")

}


#######################################################
## adding to scMutiome object
Misc(scMultiome, slot = "Combined_DEGs_GRN") <- combined_grn_list  ## list to save as tbl_graph object
Misc(scMultiome, slot = "Cluster_DEGs_GRN") <- grn_list

print("The gene regulatory network has been successfully completed!!")

}

################
## output Rdata
################
saveRDS(scMultiome, file = paste0(out_dir, sample_id, "_extended_seurat_object.RDS"))
write.csv(scMultiome@meta.data,  file = paste0(out_dir, sample_id, "_extended_meta_data.csv"))

print("The main seurat has been successfully executed !!")
